language: node_js
node_js:
  - lts/dubnium
  - node
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: RWSe+VT69ZWtHboTg0GdMKi3QK+VZINO1yG19tZhNGQjCARo0j2k604rxgiCEeUpVEkDGG600J5cf9Xsc+AsF2beUhKtpcKAc0hyRzTgSfguq0L9TLVobVQTk6Zx2r7cqlnx/Jnhc6A+YrcNNAXiJNsA5K0/xAhEXo/Dx6N1BbnC50t+X0yPrN3khumkheiBzQ9YtSwXLa7jqopEcDWsQIwGIsN/dJEOy+fZq0DMHaRx/oBW0HrZWYdvcozZ8tY+lF7oDnxPUHmJ8UE3LP/kuesnK7lPj/o6SZIFJJk6IyGGlaGEgjYM7yz4WOmsxW9MhqTtDhaYsseyspTQSbrP15UBVp4VEiEKlLJbJA8EqzqFu+DTA60+Vz8iCF42gvRTOlUix9U2Gq+BSdIUjCzPJw84lOR1YtALjQGgbmfvXR5myaXuWVc5U8KCqdb4q0skHupDbawt+jdMlkFIcx5B4YLHnhK2Re9/3PWkPdRjqqYfGpV0Dq7qc3OPX37u7ihkrGmleZ30q/yqHUL21FdYxyd0H+ruLTYNg/TqxbzjovBT7OQlXjcTq5Mi9zx4WJ+ZtRWsFf3BT2hqKs8PRkLfnS4x3gEB8wnnljUn6jKy1yk8PbFF7/QZWUXNrEo0QzxacvsqHYt8mcMs0i3lp22GlTUAqEDUPLcnL4brbo+Z0eU=
  file:
    - 'unherit.js'
    - 'unherit.min.js'
  on:
    tags: true
