language: node_js
node_js:
- lts/boron
- node
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: l0tzWp3uoIIqSMfKuh5pXIjEEQIjlfukMA63WNUNRw390UC5P0OunH5owrdQUGFHOYxkSsqNRJaM5g56uto8ixwlWcvB69mr9iGxYf+ZoxZkP8zjWENsLe6goYyTVXNHC14OSSqnpAg0yWYHBOtTxpQc78o93q4VNo0lVBRATTUUiZ5fVVvQ8Gx0XcVwZTNEag5bODsqsxKoRdqLLTAv2aljiq3DOp89JcxNvYOhUDnKntp6/vqUUkIcYkWjc9FaV8bVpgb4zzd7Ipa90QfsZzH+IteW9EOy9hC29XagVG40et+FojG2mQdit9XDWF9XbQkPJ/QevmKEb+6AZ95cPlNgrrxuv76/eyFFEcLoWKUYhlqsTFxr5kDVZxDreTQcFkaDhUODiOTUUm7312wVWTeKovfhQwsLUwi8TzBgukfmun7XIStcUTqNrF6kmbo1jDLq7Btd44uGPZnTPiu3F//Be/kRUzfgiSpEaI7aZaOBnCrLHuP0kEtPSzk4eZ4idK7iRZ/hSVnyas4P4o1jg7lrLuMmiqfM9NaxdNGgjJqkbP9oWrWQ7aooUKsQ0fvSLJdRaCeBXJ7EuRBXKJjWXhovfg4cDi2fXP9zG3kKzyLM16d2ZBdJVtKDJn0BXE80EjC4rWqVxH2vcEqwUPVqYX39lGniJGKyU7LlA77bFds=
  file:
    - "unherit.js"
    - "unherit.min.js"
  on:
    tags: true
